version: '3.5'

services:

  zookeeper:
    image: "wurstmeister/zookeeper:latest"
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    depends_on:
      - zookeeper
    container_name: "kafka"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'SSL://kafka:9092'
      KAFKA_LISTENERS: 'SSL://0.0.0.0:9092'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_SSL_KEYSTORE_LOCATION: '/certs/kafka.server.keystore.jks'
      KAFKA_SSL_KEYSTORE_PASSWORD: 'password'
      KAFKA_SSL_KEY_PASSWORD: 'password'
      KAFKA_SSL_TRUSTSTORE_LOCATION: '/certs/kafka.server.truststore.jks'
      KAFKA_SSL_TRUSTSTORE_PASSWORD: 'password'
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_SECURITY_PROTOCOL: SSL
      KAFKA_CREATE_TOPICS: "piilog:1:1"

    volumes:
      - .:/certs
    networks:
      - kafka-net
networks:
  kafka-net:
    driver: bridge